### ISSUE TITLE
refactor tool is a little opinionated :)

### ISSUE THREAD

**Issue by DGollings** [gp-pereira/refactorex#4]
RefactorEx changes formatting, for example

```elixir
[] |> Enum.map(fn a -> a end) |> List.first()
```

Which is perfectly fine, simple and short enough to be readable and passes any of my formatters

Hitting `F2` and renaming `a` to `b` results in 

```elixir
[]
|> Enum.map(fn b -> b end)
|> List.first()
```

Which is fine, but does add an extra 'unnecessary' formatting change and thus a larger, more difficult to read diff

(marginally, this is all minor, but considering it was valid code in the first place I'd say more bug than feature)

**Comment by gp-pereira** [comment]
Definetily would mark as bug as well specially because of the harder diffs part. I'll take a look soon

**Comment by gp-pereira** [comment]
Hello, i found the problem. The issue was the placeholder name I was using for the renamers was too long (: name_being_refactored_31_08_2003), so when rendered, it automatically formated the code like that. v0.1.27 is using a way shorter name (:__y__) and in the test it didn't introduce extra newlines anymore.

**Comment by gp-pereira** [comment]
Hello, i found the problem. The issue was the placeholder name I was using for the renamers was too long (: name_being_refactored_31_08_2003), so when rendered, it automatically formated the code like that. v0.1.27 is using a way shorter name (:__y__) and in the tests it didn't introduce extra newlines anymore.
